/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaapplication7;
import java.sql.*;
import java.awt.*;
import javax.swing.*;
import java. *;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class vendedor extends javax.swing.JFrame {

    /**
     * Creates new form vendedor
     */
    public vendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setLabel("CANTIDAD PRODUCTO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setLabel("CLIENTES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setLabel("EMPLEADOS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setLabel("COSTOS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setLabel("EMPLEADOS Y FACTURAS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setLabel("CREAR FACTURA");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setLabel("INCERTAR COMPRA");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setLabel("INCERTAR TELEFONO");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setLabel("SALIR");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(3, 3, 3)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // VISTA 5
        try{
         Statement cmd = conexion.conexion.createStatement();
         ResultSet rcmd = cmd.executeQuery ("select * from info_factu");
         String datos = "";
         while (rcmd.next())
         {
             datos = datos +"NOMBRE:"+ rcmd.getString("emp_nombreApellido")+
                     " ID FACTURA: "+ rcmd.getInt("fac_id") +
                     " FECHA: "+ rcmd.getDate("fac_fecha") +
                     "\n"; 
         } 
          jTextArea1.setText(datos);
       }catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Imposible cargar vista ...Error.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // VISTA 1
        try{
         Statement cmd = conexion.conexion.createStatement();
         ResultSet rcmd = cmd.executeQuery ("select * from productos");
         String datos = "";
         while (rcmd.next())
         {
             datos = datos +"NOMBRE:"+ rcmd.getString("pro_nombre")+" CANTIDAD: "+ rcmd.getString("pro_cantidad") + "\n"; 
         } 
          jTextArea1.setText(datos);
       }catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Imposible cargar vista ...Error.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //vsita 2
         try{
         Statement cmd = conexion.conexion.createStatement();
         ResultSet rcmd = cmd.executeQuery ("select * from nom_tel_cli");
         String datos = "";
         while (rcmd.next())
         {
             datos = datos +"NOMBRE CLIENTE:"+ rcmd.getString("cli_nombre")+" TELEFONO: "+ rcmd.getString("tel_numero") + "\n"; 
         } 
          jTextArea1.setText(datos);
       }catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Imposible cargar vista ...Error.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         //vsita 3
         try{
         Statement cmd = conexion.conexion.createStatement();
         ResultSet rcmd = cmd.executeQuery ("select * from nom_tl_EmpFA");
         String datos = "";
         while (rcmd.next())
         {
             datos = datos +"NOMBRE EMPLEADO:"+ rcmd.getString("emp_nombreApellido")+" TELEFONO EMPLEADO: "+ rcmd.getString("tel_numero") + "\n"; 
         } 
          jTextArea1.setText(datos);
       }catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Imposible cargar vista ...Error.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //vsita 4
         try{
         Statement cmd = conexion.conexion.createStatement();
         ResultSet rcmd = cmd.executeQuery ("select * from produ_prec");
         String datos = "";
         while (rcmd.next())
         {
             datos = datos +" NOMBRE:"+ rcmd.getString("pro_nombre")+" COSTO: "+ rcmd.getString("prec_costo") + "\n"; 
         } 
          jTextArea1.setText(datos);
       }catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Imposible cargar vista ...Error.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         try {        
            //PROCEDIMIENTO 1
            String idfactura = JOptionPane.showInputDialog(null, "Por favor digite el numero de factura nuevo", null, WIDTH);
            String idcliente = JOptionPane.showInputDialog(null, "Por favor digite la identificacion del cliente", null, WIDTH);
            String clienteNombre = JOptionPane.showInputDialog(null, "Por favor digite el nombre del cliente", null, WIDTH);
            String clienteDireccion = JOptionPane.showInputDialog(null, "Por favor digite la direccion del cliente", null, WIDTH);
            String clienteTelefono = JOptionPane.showInputDialog(null, "Por favor digite el telefono del cliente", null, WIDTH);
            String empleadoId = JOptionPane.showInputDialog(null, "Por favor digite la identificaciondel empleado", null, WIDTH);
            int idFac = Integer.parseInt(idfactura);
            int idCli = Integer.parseInt(idcliente);
            int cliTel = Integer.parseInt(clienteTelefono);
            int empId = Integer.parseInt(empleadoId);
            CallableStatement cmd = conexion.conexion.prepareCall("{call crear_factura (?,?,?,?,?,?)}");
            
            cmd.setInt(1,idFac);
            cmd.setInt(2,idCli);
            cmd.setString(3,clienteNombre);
            cmd.setString(4,clienteDireccion);
            cmd.setInt(5,cliTel);
            cmd.setInt(6,empId);
            System.out.println(idFac);
            cmd.execute();
            System.out.println(idFac);
            cmd.close();
            String datos = "se ha ingresado correctamente la factura ";
            jTextArea1.setText(datos);
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Imposible cargar valor ...Error.", "Error", JOptionPane.ERROR_MESSAGE);
        System.out.println(ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {        
            //PROCEDIMIENTO 2
            String idfactura = JOptionPane.showInputDialog(null, "Por favor digite el numero de factura a la que desea agregar el producto", null, WIDTH);
            String idProducto = JOptionPane.showInputDialog(null, "Por favor digite el id del producto", null, WIDTH);
            String cantidad = JOptionPane.showInputDialog(null, "Por favor digite la cantidad que desa comprarde este producto", null, WIDTH);
            int idFac = Integer.parseInt(idfactura);
            int idPro = Integer.parseInt(idProducto);
            int Cant = Integer.parseInt(cantidad);
            CallableStatement cmd = conexion.conexion.prepareCall("{call adicionar_compra (?,?,?)}");
            cmd.setInt(1,idFac);
            cmd.setInt(2,idPro);
            cmd.setInt(3,Cant);
            System.out.println(idFac);
            cmd.execute();
            System.out.println(idFac);
            cmd.close();
            String datos = "se ha ingresado el producto correctamente la factura ";
            jTextArea1.setText(datos);
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Imposible cargar valor ...Error.", "Error", JOptionPane.ERROR_MESSAGE);
        System.out.println(ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {        
            //PROCEDIMIENTO 3
            String idCliente = JOptionPane.showInputDialog(null, "Por favor digite la identificacion del cliente", null, WIDTH);
            String telefono = JOptionPane.showInputDialog(null, "Por favor digite el telefono a ingresar", null, WIDTH);
            int idPro = Integer.parseInt(idCliente);
            int Cant = Integer.parseInt(telefono);
            int val = 0;
            CallableStatement cmd = conexion.conexion.prepareCall("{call incertar_telefono (?,?,?)}");
            cmd.setInt(1,val);
            cmd.setInt(2,idPro);
            cmd.setInt(3,Cant);
            System.out.println(Cant);
            cmd.execute();
            System.out.println(Cant);
            cmd.close();
            String datos = "se ha ingresado el telefono correctamente la factura ";
            jTextArea1.setText(datos);
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Imposible cargar valor ...Error.", "Error", JOptionPane.ERROR_MESSAGE);
        System.out.println(ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       try {
        conexion.conexion.close();
        JOptionPane.showMessageDialog(null, "Cerrar conexión a base de datos "+conexion.server+" exitosa.", "Conexión cerrada", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
        super.setVisible(false);        
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Imposible cerrar conexion con "+conexion.server+"...Error.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
